// Code generated by wit-bindgen-go. DO NOT EDIT.

package random

import (
	"internal/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:random@0.2.0".

//go:wasmimport wasi:random/random@0.2.0 get-random-bytes
//go:noescape
func wasmimport_GetRandomBytes(len0 uint64, result *cm.List[uint8])

//go:wasmimport wasi:random/random@0.2.0 get-random-u64
//go:noescape
func wasmimport_GetRandomU64() (result0 uint64)
