//go:build esp32s3_wroom1

package machine

const (
	SPI1_SCK_PIN  = GPIO12 // SCK
	SPI1_MOSI_PIN = GPIO11 // SDO (MOSI)
	SPI1_MISO_PIN = GPIO13 // SDI (MISO)
	SPI1_CS_PIN   = GPIO10 // CS

	SPI2_SCK_PIN  = GPIO36 // SCK
	SPI2_MOSI_PIN = GPIO35 // SDO (MOSI)
	SPI2_MISO_PIN = GPIO37 // SDI (MISO)
	SPI2_CS_PIN   = GPIO34 // CS
)
