//go:build gc.boehm && tinygo.wasm

package runtime

import "unsafe"

func markGlobals() {
	rangeCount := gcGlobalRootCount()
	if rangeCount == 0 {
		return
	}

	var rootCount uintptr
	for i := uintptr(0); i < rangeCount; i++ {
		rootCount += gcGlobalRootSize(i) / unsafe.Sizeof(uintptr(0))
	}

	// markRoots only accepts a range, so copy all global pointers into
	// contiguous scratch space for marking.
	roots := unsafe.Slice((*uintptr)(gcGlobalRootValues()), rootCount)
	var rootIndex uintptr
	for i := uintptr(0); i < rangeCount; i++ {
		addr := gcGlobalRoot(i)
		size := gcGlobalRootSize(i)
		for offset := uintptr(0); offset < size; offset += unsafe.Sizeof(uintptr(0)) {
			roots[rootIndex] = *(*uintptr)(unsafe.Add(addr, offset))
			rootIndex++
		}
	}

	start := uintptr(unsafe.Pointer(&roots[0]))
	markRoots(start, start+rootCount*unsafe.Sizeof(roots[0]))
}

// These functions are generated by the compiler from the pointer layouts of
// mutable globals. Each range contains only pointer slots.
func gcGlobalRootCount() uintptr
func gcGlobalRoot(index uintptr) unsafe.Pointer
func gcGlobalRootSize(index uintptr) uintptr
func gcGlobalRootValues() unsafe.Pointer
