//go:build gc.boehm && tinygo.wasm

package runtime

import "unsafe"

func markGlobals() {
	count := gcGlobalRootCount()
	if count == 0 {
		return
	}

	// markRoots only accepts a range, so copy all global pointers into
	// contiguous scratch space for marking.
	roots := unsafe.Slice((*uintptr)(gcGlobalRootValues()), count)
	for i := range roots {
		addr := gcGlobalRoot(uintptr(i))
		roots[i] = *(*uintptr)(addr)
	}

	start := uintptr(unsafe.Pointer(&roots[0]))
	markRoots(start, start+count*unsafe.Sizeof(roots[0]))
}

// These functions are generated by the compiler from the pointer layouts of
// mutable globals.
func gcGlobalRootCount() uintptr
func gcGlobalRoot(index uintptr) unsafe.Pointer
func gcGlobalRootValues() unsafe.Pointer
