//go:build (gc.conservative || gc.precise) && tinygo.wasm

package runtime

import "unsafe"

func markGlobals() {
	for i := uintptr(0); i < gcGlobalRootCount(); i++ {
		addr := gcGlobalRoot(i)
		markRoot(uintptr(addr), *(*uintptr)(addr))
	}
}

// These functions are generated by the compiler from the pointer layouts of
// mutable globals.
func gcGlobalRootCount() uintptr
func gcGlobalRoot(index uintptr) unsafe.Pointer
