//go:build (gc.conservative || gc.precise) && tinygo.wasm

package runtime

import "unsafe"

func markGlobals() {
	for i := uintptr(0); i < gcGlobalRootCount(); i++ {
		addr := gcGlobalRoot(i)
		size := gcGlobalRootSize(i)
		for offset := uintptr(0); offset < size; offset += unsafe.Sizeof(uintptr(0)) {
			slot := unsafe.Add(addr, offset)
			markRoot(uintptr(slot), *(*uintptr)(slot))
		}
	}
}

// These functions are generated by the compiler from the pointer layouts of
// mutable globals. Each range contains only pointer slots.
func gcGlobalRootCount() uintptr
func gcGlobalRoot(index uintptr) unsafe.Pointer
func gcGlobalRootSize(index uintptr) uintptr
