// +build nxp,mimxrt1062

package runtime

import "device/nxp"

const (
	CFSR_IACCVIOL    = nxp.SCB_CFSR_IACCVIOL
	CFSR_DACCVIOL    = nxp.SCB_CFSR_DACCVIOL
	CFSR_MUNSTKERR   = nxp.SCB_CFSR_MUNSTKERR
	CFSR_MSTKERR     = nxp.SCB_CFSR_MSTKERR
	CFSR_MLSPERR     = nxp.SCB_CFSR_MLSPERR
	CFSR_IBUSERR     = nxp.SCB_CFSR_IBUSERR
	CFSR_PRECISERR   = nxp.SCB_CFSR_PRECISERR
	CFSR_IMPRECISERR = nxp.SCB_CFSR_IMPRECISERR
	CFSR_UNSTKERR    = nxp.SCB_CFSR_UNSTKERR
	CFSR_STKERR      = nxp.SCB_CFSR_STKERR
	CFSR_LSPERR      = nxp.SCB_CFSR_LSPERR
	CFSR_UNDEFINSTR  = nxp.SCB_CFSR_UNDEFINSTR
	CFSR_INVSTATE    = nxp.SCB_CFSR_INVSTATE
	CFSR_INVPC       = nxp.SCB_CFSR_INVPC
	CFSR_NOCP        = nxp.SCB_CFSR_NOCP
	CFSR_UNALIGNED   = nxp.SCB_CFSR_UNALIGNED
	CFSR_DIVBYZERO   = nxp.SCB_CFSR_DIVBYZERO
	CFSR_MMARVALID   = nxp.SCB_CFSR_MMARVALID
	CFSR_BFARVALID   = nxp.SCB_CFSR_BFARVALID
)
