// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package streams

import (
	"unsafe"
)

// StreamErrorShape is used for storage in variant or result types.
type StreamErrorShape struct {
	shape [unsafe.Sizeof(StreamError{})]byte
}
