// Code generated by wit-bindgen-go. DO NOT EDIT.

package run

import (
	"internal/cm"
)

// Exports represents the caller-defined exports from "wasi:cli/run@0.2.0".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	// Run the program.
	//
	//	run: func() -> result
	Run func() (result cm.BoolResult)
}
