// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package run

import (
	"github.com/ydnar/wasm-tools-go/cm"
)

// Exports represents the caller-defined exports from "wasi:cli/run@0.2.0".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	// Run the program.
	//
	//	run: func() -> result
	Run func() (result cm.Result)
}
