// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package types

import (
	"github.com/ydnar/wasm-tools-go/cm"
	wallclock "internal/wasi/clocks/v0.2.0/wall-clock"
)

func lower_DateTime(v wallclock.DateTime) (f0 uint64, f1 uint32) {
	f0 = (uint64)(v.Seconds)
	f1 = (uint32)(v.Nanoseconds)
	return
}

func lower_NewTimestamp(v NewTimestamp) (f0 uint32, f1 uint64, f2 uint32) {
	f0 = (uint32)(cm.Tag(&v))
	switch f0 {
	case 2: // timestamp
		v1, v2 := lower_DateTime(*v.Timestamp())
		f1 = (uint64)(v1)
		f2 = (uint32)(v2)
	}
	return
}
